server:
  port: 8080

logging:
  file.path: logs
  file.name: mylog.log

spring:
  application:
    name: report
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.xxx.xxx:3306/o2o?useUnicode=true&characterEncoding=utf8
    username: xxxx
    password: xxxx

mybatis:
  type-aliases-package: com.houle.demo.model
  mapper-locations: mapper/*